/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package quanlybaotang;

import Helper.DataValidator;

import Helper.MessageDialogHelper;
import dao.GianHangDao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.GianHang;

/**
 *
 * @author Doan Long Vu
 */
public class QuanLyGianTrungBayPanel extends javax.swing.JPanel {
    private QuanLyBaoTangForm parentForm;
    private DefaultTableModel tblModel;
            
    String TimKiem = "";
    public QuanLyGianTrungBayPanel() {
        initComponents();
        initTable();
        loadDataToTable();
    }
    // Thêm bảng 
    private void initTable(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã Gian Hàng", "Gian Trưng Bày", "Diện Tích", "Vị Trí Gian Trưng Bày", "Quạt Làm Mát", "Bàn Ghế"});
        tblGianHang.setModel(tblModel);
    }
    private void loadDataToTable(){ //Load dữ liệu từ sql lên bảng
        try {
            GianHangDao dao = new GianHangDao();
            List<GianHang> list = dao.findAll();
            tblModel.setRowCount(0);
            for (GianHang gh : list) {
                tblModel.addRow(new Object[]{
                    gh.getMaGianHangTrungBay(), gh.getGianTrungBay()==1? "Tiêu chuẩn" : "Cao cấp", gh.getDienTich(), 
                    gh.getViTriGianTrungBay(), gh.getQuatLamMat(), gh.getBanGhe()
                });
            }
            tblModel.fireTableDataChanged();
        } catch (Exception e){
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtViTriGianTrungBay = new javax.swing.JTextField();
        txtMaGianHang = new javax.swing.JTextField();
        txtDienTich = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rdbTieuChuan = new javax.swing.JRadioButton();
        rdbCaoCap = new javax.swing.JRadioButton();
        btnThem = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGianHang = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtQuatLamMat = new javax.swing.JTextField();
        txtBanGhe = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtMaGianHangSearch = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("GIAN HÀNG TRƯNG BÀY");

        jLabel2.setText("Mã Gian Hàng");

        jLabel3.setText("Gian Trưng Bày");

        jLabel4.setText("Diện Tích");

        txtMaGianHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaGianHangActionPerformed(evt);
            }
        });

        txtDienTich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDienTichActionPerformed(evt);
            }
        });

        jLabel5.setText("Vị Trí Gian Trưng Bày");

        buttonGroup1.add(rdbTieuChuan);
        rdbTieuChuan.setText("Tiêu Chuẩn");
        rdbTieuChuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTieuChuanActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbCaoCap);
        rdbCaoCap.setText("Cao Cấp");
        rdbCaoCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCaoCapActionPerformed(evt);
            }
        });

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/apps-add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/disk.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh (2).png"))); // NOI18N
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/trash.png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        tblGianHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblGianHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGianHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblGianHang);

        jLabel6.setText("Quạt Làm Mát");

        jLabel7.setText("Bàn Ghế");

        txtQuatLamMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuatLamMatActionPerformed(evt);
            }
        });

        txtBanGhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBanGheActionPerformed(evt);
            }
        });

        jLabel8.setText("m²");

        jLabel9.setText("Cái");

        jLabel10.setText("Cái");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel11.setText("TÌM KIẾM");

        jLabel12.setText("Nhập Mã Gian Hàng");

        txtMaGianHangSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaGianHangSearchActionPerformed(evt);
            }
        });

        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search (1).png"))); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(171, 171, 171)
                                .addComponent(btnLuu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCapNhat))
                            .addComponent(jLabel1))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtBanGhe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                            .addComponent(txtQuatLamMat, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)))
                                    .addComponent(txtViTriGianTrungBay, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMaGianHang, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(39, 39, 39))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(47, 47, 47)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(rdbTieuChuan)
                                        .addComponent(txtDienTich, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(51, 51, 51)
                                            .addComponent(rdbCaoCap))
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXoa)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(txtMaGianHangSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnTim)
                        .addGap(106, 106, 106))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaGianHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(rdbTieuChuan)
                            .addComponent(rdbCaoCap))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDienTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtViTriGianTrungBay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtQuatLamMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtBanGhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaGianHangSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTim)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnLuu)
                    .addComponent(btnCapNhat)
                    .addComponent(btnXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rdbTieuChuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTieuChuanActionPerformed
        if(rdbTieuChuan.isSelected()== true){        
            // Trường quạt và bàn ghế sẽ không cho người dùng nhập và có dữ liệu là 0
            txtQuatLamMat.setText("0");
            txtBanGhe.setText("0");
            txtQuatLamMat.setEnabled(false);
            txtBanGhe.setEnabled(false);
        }
    }//GEN-LAST:event_rdbTieuChuanActionPerformed

    private void txtMaGianHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaGianHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaGianHangActionPerformed

    private void txtQuatLamMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuatLamMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuatLamMatActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        txtBanGhe.setText("");
        txtDienTich.setText("");
        txtMaGianHang.setText("");
        txtMaGianHang.setEnabled(true);
        txtQuatLamMat.setText("");
        txtViTriGianTrungBay.setText("");
        rdbTieuChuan.setSelected(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtMaGianHang, sb, "Mã gian hàng không được để trống");
        if(sb.length()>0){
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        if(MessageDialogHelper.showConfirmDialog(parentForm,
                "Bạn có muốn xoá gian hàng không ?", "Hỏi") == JOptionPane.NO_OPTION){
            return;
        }
        try {   
            GianHangDao dao = new GianHangDao();
            if (dao.delete(txtMaGianHang.getText())){
                MessageDialogHelper.showMessageDialog(parentForm, "Xoá gian hàng thành công !", "Thông báo");
                btnThemActionPerformed(evt);
                loadDataToTable();
            } else {
                MessageDialogHelper.showConfirmDialog(parentForm, "Không xoá được gian hàng do lỗi !", "Cảnh báo");
            }
        } catch (Exception e) {
           e.printStackTrace();
           MessageDialogHelper.showErrorDialog(parentForm,e.getMessage(), "Lỗi");          
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void rdbCaoCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCaoCapActionPerformed
        if(rdbCaoCap.isSelected()== true){
            txtQuatLamMat.setText("");
            txtBanGhe.setText("");
            txtQuatLamMat.setEnabled(true);
            txtBanGhe.setEnabled(true);
        }
    }//GEN-LAST:event_rdbCaoCapActionPerformed

    private void txtDienTichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDienTichActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDienTichActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtMaGianHang, sb, "Mã gian hàng không được để trống");
        DataValidator.validateEmpty(txtDienTich, sb, "Diện tích không được để trống");
        DataValidator.validateEmpty(txtQuatLamMat, sb, "Quạt làm mát không được để trống");
        if(sb.length()>0){
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        try {
            GianHang gh = new GianHang();
            gh.setMaGianHangTrungBay(txtMaGianHang.getText());
            gh.setViTriGianTrungBay(txtViTriGianTrungBay.getText());
            gh.setDienTich(Integer.parseInt(txtDienTich.getText()));
            gh.setQuatLamMat(Integer.parseInt(txtQuatLamMat.getText()));
            gh.setBanGhe(Integer.parseInt(txtBanGhe.getText()));
            gh.setGianTrungBay(rdbTieuChuan.isSelected()?1:0);

            GianHangDao dao = new GianHangDao();
            if (dao.insert(gh)){
                MessageDialogHelper.showMessageDialog(parentForm, "Gian hàng đã được lưu !", "Thông báo");
                loadDataToTable();
            } else {
                MessageDialogHelper.showConfirmDialog(parentForm, "Không lưu được gian hàng do lỗi !", "Cảnh báo");
            }
        } catch (Exception e) {
           e.printStackTrace();
           MessageDialogHelper.showErrorDialog(parentForm,e.getMessage(), "Lỗi");          
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtMaGianHang, sb, "Mã gian hàng không được để trống");
        DataValidator.validateEmpty(txtDienTich, sb, "Diện tích không được để trống");
        DataValidator.validateEmpty(txtQuatLamMat, sb, "Quạt làm mát không được để trống");
        if(sb.length()>0){
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        try {
            GianHang gh = new GianHang();
            gh.setMaGianHangTrungBay(txtMaGianHang.getText());
            gh.setViTriGianTrungBay(txtViTriGianTrungBay.getText());
            gh.setDienTich(Integer.parseInt(txtDienTich.getText()));
            gh.setQuatLamMat(Integer.parseInt(txtQuatLamMat.getText()));
            gh.setBanGhe(Integer.parseInt(txtBanGhe.getText()));
            gh.setGianTrungBay(rdbTieuChuan.isSelected()?1:0);
            
            GianHangDao dao = new GianHangDao();
            if (dao.update(gh)){
                MessageDialogHelper.showMessageDialog(parentForm, "Gian hàng cập nhật thành công !", "Thông báo");
                loadDataToTable();
            } else {
                MessageDialogHelper.showConfirmDialog(parentForm, "Không cập nhật được gian hàng do lỗi !", "Cảnh báo");
            }
        } catch (Exception e) {
           e.printStackTrace();
           MessageDialogHelper.showErrorDialog(parentForm,e.getMessage(), "Lỗi");          
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    public void display() {//chọn gian hàng hiện lên form
        int currentRow = tblGianHang.getSelectedRow();
        if (currentRow >= 0) {
            txtMaGianHang.setText(tblGianHang.getValueAt(currentRow, 0).toString());
            txtMaGianHang.setEnabled(false);
            if (tblGianHang.getValueAt(currentRow, 1).equals("Tiêu chuẩn")) {
            rdbTieuChuan.setSelected(true);
            txtBanGhe.setEnabled(false);
            txtQuatLamMat.setEnabled(false);
        } else {
            rdbCaoCap.setSelected(true);
            txtQuatLamMat.setEnabled(true);
            txtBanGhe.setEnabled(true);
        } txtDienTich.setText(tblGianHang.getValueAt(currentRow, 2).toString());
            txtViTriGianTrungBay.setText(tblGianHang.getValueAt(currentRow, 3).toString());
            txtQuatLamMat.setText(tblGianHang.getValueAt(currentRow, 4).toString());
            txtBanGhe.setText(tblGianHang.getValueAt(currentRow, 5).toString());
        }
    }
    
    private void tblGianHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGianHangMouseClicked
        try{
        display();
        } catch (Exception e){
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_tblGianHangMouseClicked

    private void txtBanGheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBanGheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBanGheActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        try {        
            TimKiem = txtMaGianHangSearch.getText();
            findByMa();
            } catch (Exception e){
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
                
           
    }//GEN-LAST:event_btnTimActionPerformed

    private void findByMa() throws Exception{

        GianHangDao dao = new GianHangDao();
        tblModel.setRowCount(0);
        for(GianHang gh : dao.findByID(TimKiem)){
            Object rowDataObject[] = new Object[6];
            rowDataObject[0] = gh.getMaGianHangTrungBay();
            rowDataObject[1] = gh.getGianTrungBay() == 1 ? "Tiêu chuẩn" : "Cao cấp";
            rowDataObject[2] = gh.getDienTich();
            rowDataObject[3] = gh.getViTriGianTrungBay();
            rowDataObject[4] = gh.getQuatLamMat();
            rowDataObject[5] = gh.getBanGhe();
            tblModel.addRow(rowDataObject);
        }
   
    }
    private void txtMaGianHangSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaGianHangSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaGianHangSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton rdbCaoCap;
    private javax.swing.JRadioButton rdbTieuChuan;
    private javax.swing.JTable tblGianHang;
    private javax.swing.JTextField txtBanGhe;
    private javax.swing.JTextField txtDienTich;
    private javax.swing.JTextField txtMaGianHang;
    private javax.swing.JTextField txtMaGianHangSearch;
    private javax.swing.JTextField txtQuatLamMat;
    private javax.swing.JTextField txtViTriGianTrungBay;
    // End of variables declaration//GEN-END:variables

}
