/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlybaotang;


/**
 *
 * @author Hoang Anh
 */
public class QuanLyBaoTangForm extends javax.swing.JFrame {
   private QuanLyGianTrungBayPanel mBaoTangPanel;
   private QuanLyKhachThuePanel mKhachThuePanel;
   private ThongTinNhomPanel mNhomPanel;

    public QuanLyBaoTangForm() {
        initComponents();

        setLocationRelativeTo(null); //để giao diện chương trình cân giữa màn hình
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        menuQuanLyBaoTang = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        menuQuanLyKhachThue = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        menuThongTinNhom = new javax.swing.JButton();
        pnMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBackground(new java.awt.Color(255, 204, 204));
        jToolBar1.setRollover(true);

        menuQuanLyBaoTang.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        menuQuanLyBaoTang.setForeground(new java.awt.Color(255, 51, 51));
        menuQuanLyBaoTang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bank.png"))); // NOI18N
        menuQuanLyBaoTang.setText("Quản Lý Bảo Tàng");
        menuQuanLyBaoTang.setFocusable(false);
        menuQuanLyBaoTang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuQuanLyBaoTang.setMaximumSize(new java.awt.Dimension(120, 48));
        menuQuanLyBaoTang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menuQuanLyBaoTang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyBaoTangActionPerformed(evt);
            }
        });
        jToolBar1.add(menuQuanLyBaoTang);
        jToolBar1.add(jSeparator1);

        menuQuanLyKhachThue.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        menuQuanLyKhachThue.setForeground(new java.awt.Color(255, 51, 51));
        menuQuanLyKhachThue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/address-book.png"))); // NOI18N
        menuQuanLyKhachThue.setText("Quản Lý Khách Thuê");
        menuQuanLyKhachThue.setFocusable(false);
        menuQuanLyKhachThue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuQuanLyKhachThue.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menuQuanLyKhachThue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuanLyKhachThueActionPerformed(evt);
            }
        });
        jToolBar1.add(menuQuanLyKhachThue);
        jToolBar1.add(jSeparator2);

        menuThongTinNhom.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        menuThongTinNhom.setForeground(new java.awt.Color(255, 0, 0));
        menuThongTinNhom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/info.png"))); // NOI18N
        menuThongTinNhom.setText("Thông Tin Nhóm ");
        menuThongTinNhom.setFocusable(false);
        menuThongTinNhom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuThongTinNhom.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menuThongTinNhom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThongTinNhomActionPerformed(evt);
            }
        });
        jToolBar1.add(menuThongTinNhom);

        pnMain.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    // Hiển thị menu chính nhập thông tin khi nhập vào các nút trên trang chính
    
    private void menuQuanLyBaoTangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyBaoTangActionPerformed
        mBaoTangPanel = new QuanLyGianTrungBayPanel();
        pnMain.removeAll();
        pnMain.add(mBaoTangPanel);
        pnMain.validate();
    }//GEN-LAST:event_menuQuanLyBaoTangActionPerformed

    private void menuThongTinNhomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThongTinNhomActionPerformed
        mNhomPanel = new ThongTinNhomPanel();
        pnMain.removeAll();
        pnMain.add(mNhomPanel);
        pnMain.validate();
    }//GEN-LAST:event_menuThongTinNhomActionPerformed

    private void menuQuanLyKhachThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuanLyKhachThueActionPerformed
       mKhachThuePanel = new QuanLyKhachThuePanel();
       pnMain.removeAll();
       pnMain.add(mKhachThuePanel);
       pnMain.validate();
    }//GEN-LAST:event_menuQuanLyKhachThueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyBaoTangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyBaoTangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyBaoTangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyBaoTangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyBaoTangForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton menuQuanLyBaoTang;
    private javax.swing.JButton menuQuanLyKhachThue;
    private javax.swing.JButton menuThongTinNhom;
    private javax.swing.JPanel pnMain;
    // End of variables declaration//GEN-END:variables
}
